name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode.app
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild -scheme CoordinateKit build -destination "generic/platform=macOS"
      - name: Build iOS
        run: xcodebuild -scheme CoordinateKit build -destination "generic/platform=iOS"
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test macOS
        run: xcodebuild -scheme CoordinateKit test -destination "platform=macOS,arch=x86_64"
      - name: Test iOS
        run: xcodebuild -scheme CoordinateKit test -destination "name=iPhone 14 Pro"
